-- Insert sample users for testing the matching system
INSERT INTO public.profiles (user_id, display_name, avatar_url, bio, mood, interests, current_intentions, connection_goals, last_conversation_topics) VALUES
(gen_random_uuid(), 'Sarah Chen', 'https://images.unsplash.com/photo-1494790108755-2616b612b3e2?w=150&h=150&fit=crop&crop=face', 'Creative writer and book enthusiast who loves exploring diverse stories and perspectives.', 'Inspired', ARRAY['Books', 'Writing', 'Asian Literature', 'Poetry'], 'Looking to connect with fellow creatives for collaborative storytelling projects', 'Creative partnerships and meaningful literary discussions', ARRAY['Creative writing techniques', 'Book recommendations', 'Cultural storytelling']),

(gen_random_uuid(), 'Marcus Johnson', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face', 'Mindfulness coach and wellness advocate focused on mental health and personal growth.', 'Peaceful', ARRAY['Mindfulness', 'Meditation', 'Mental Health', 'Wellness'], 'Seeking connections with people interested in personal development and inner peace', 'Supportive conversations about growth and well-being', ARRAY['Meditation practices', 'Stress management', 'Life balance']),

(gen_random_uuid(), 'Elena Rodriguez', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face', 'Career transition specialist helping professionals navigate new opportunities and challenges.', 'Hopeful', ARRAY['Career Development', 'Leadership', 'Professional Growth', 'Networking'], 'Connecting with professionals in career transitions or leadership roles', 'Professional mentorship and career guidance exchanges', ARRAY['Career strategy', 'Leadership skills', 'Industry insights']),

(gen_random_uuid(), 'David Kim', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face', 'Tech entrepreneur and innovation enthusiast passionate about startups and emerging technologies.', 'Energized', ARRAY['Technology', 'Startups', 'Innovation', 'Entrepreneurship'], 'Looking for co-founders and fellow entrepreneurs for brainstorming and collaboration', 'Business partnerships and tech innovation discussions', ARRAY['Startup strategies', 'Tech trends', 'Business development']),

(gen_random_uuid(), 'Aisha Patel', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=150&h=150&fit=crop&crop=face', 'Philosophy student and deep thinker who enjoys exploring life''s big questions and meaningful conversations.', 'Reflective', ARRAY['Philosophy', 'Psychology', 'Deep Conversations', 'Personal Growth'], 'Seeking intellectually stimulating discussions about life, meaning, and human nature', 'Philosophical exchanges and deep meaningful connections', ARRAY['Life philosophy', 'Human psychology', 'Existential questions']);